// <auto-generated />
using System;
using BibliothequeManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliothequeManager.Migrations
{
    [DbContext(typeof(BibliothequeContext))]
    [Migration("20251205040740_chagementBD")]
    partial class chagementBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliothequeManager.Models.Adherent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amandes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCarte")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NumeroCarte")
                        .IsUnique();

                    b.ToTable("Adherents");
                });

            modelBuilder.Entity("BibliothequeManager.Models.Auteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Auteurs");
                });

            modelBuilder.Entity("BibliothequeManager.Models.Bibliothecaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Bibliothecaires");
                });

            modelBuilder.Entity("BibliothequeManager.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BibliothequeManager.Models.Emprunt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdherentId")
                        .HasColumnType("int");

                    b.Property<int>("BibliothecaireEmpruntId")
                        .HasColumnType("int");

                    b.Property<int?>("BibliothecaireRetourId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEmprunt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRetourPrevu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRetourReel")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExemplaireId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdherentId");

                    b.HasIndex("BibliothecaireEmpruntId");

                    b.HasIndex("BibliothecaireRetourId");

                    b.HasIndex("ExemplaireId");

                    b.ToTable("Emprunts");
                });

            modelBuilder.Entity("BibliothequeManager.Models.Exemplaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeBarre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EstDisponible")
                        .HasColumnType("bit");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("LivreId")
                        .HasColumnType("int");

                    b.Property<int>("NombrePage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodeBarre")
                        .IsUnique();

                    b.HasIndex("LivreId");

                    b.ToTable("Exemplaires");
                });

            modelBuilder.Entity("BibliothequeManager.Models.LivreCategorie", b =>
                {
                    b.Property<int>("LivreId")
                        .HasColumnType("int");

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.HasKey("LivreId", "CategorieId");

                    b.HasIndex("CategorieId");

                    b.ToTable("LivreCategories");
                });

            modelBuilder.Entity("BibliothequeManager.Models.Livres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuteurId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Livres");
                });

            modelBuilder.Entity("BibliothequeManager.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdherentId")
                        .HasColumnType("int");

                    b.Property<int>("BibliothecaireId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateReservation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRetour")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExemplaireAttribueId")
                        .HasColumnType("int");

                    b.Property<int>("LivreId")
                        .HasColumnType("int");

                    b.Property<string>("Priorite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdherentId");

                    b.HasIndex("BibliothecaireId");

                    b.HasIndex("ExemplaireAttribueId");

                    b.HasIndex("LivreId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("BibliothequeManager.Models.Emprunt", b =>
                {
                    b.HasOne("BibliothequeManager.Models.Adherent", "Adherent")
                        .WithMany("Emprunts")
                        .HasForeignKey("AdherentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliothequeManager.Models.Bibliothecaire", "BibliothecaireEmprunt")
                        .WithMany("EmpruntsEnregistres")
                        .HasForeignKey("BibliothecaireEmpruntId")
                        .IsRequired();

                    b.HasOne("BibliothequeManager.Models.Bibliothecaire", "BibliothecaireRetour")
                        .WithMany("EmpruntsRetournes")
                        .HasForeignKey("BibliothecaireRetourId");

                    b.HasOne("BibliothequeManager.Models.Exemplaire", "Exemplaire")
                        .WithMany("Emprunts")
                        .HasForeignKey("ExemplaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Adherent");

                    b.Navigation("BibliothecaireEmprunt");

                    b.Navigation("BibliothecaireRetour");

                    b.Navigation("Exemplaire");
                });

            modelBuilder.Entity("BibliothequeManager.Models.Exemplaire", b =>
                {
                    b.HasOne("BibliothequeManager.Models.Livres", "Livre")
                        .WithMany("Exemplaires")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("BibliothequeManager.Models.LivreCategorie", b =>
                {
                    b.HasOne("BibliothequeManager.Models.Categorie", "Categorie")
                        .WithMany("LivreCategories")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibliothequeManager.Models.Livres", "Livre")
                        .WithMany("LivreCategories")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("BibliothequeManager.Models.Livres", b =>
                {
                    b.HasOne("BibliothequeManager.Models.Auteur", "Auteur")
                        .WithMany("Livres")
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auteur");
                });

            modelBuilder.Entity("BibliothequeManager.Models.Reservation", b =>
                {
                    b.HasOne("BibliothequeManager.Models.Adherent", "Adherent")
                        .WithMany("Reservations")
                        .HasForeignKey("AdherentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliothequeManager.Models.Bibliothecaire", "Bibliothecaire")
                        .WithMany("Reservations")
                        .HasForeignKey("BibliothecaireId")
                        .IsRequired();

                    b.HasOne("BibliothequeManager.Models.Exemplaire", "ExemplaireAttribue")
                        .WithMany()
                        .HasForeignKey("ExemplaireAttribueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BibliothequeManager.Models.Livres", "Livre")
                        .WithMany("Reservations")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Adherent");

                    b.Navigation("Bibliothecaire");

                    b.Navigation("ExemplaireAttribue");

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("BibliothequeManager.Models.Adherent", b =>
                {
                    b.Navigation("Emprunts");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("BibliothequeManager.Models.Auteur", b =>
                {
                    b.Navigation("Livres");
                });

            modelBuilder.Entity("BibliothequeManager.Models.Bibliothecaire", b =>
                {
                    b.Navigation("EmpruntsEnregistres");

                    b.Navigation("EmpruntsRetournes");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("BibliothequeManager.Models.Categorie", b =>
                {
                    b.Navigation("LivreCategories");
                });

            modelBuilder.Entity("BibliothequeManager.Models.Exemplaire", b =>
                {
                    b.Navigation("Emprunts");
                });

            modelBuilder.Entity("BibliothequeManager.Models.Livres", b =>
                {
                    b.Navigation("Exemplaires");

                    b.Navigation("LivreCategories");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
