//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliothequeManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BibliothequeManager.Properties.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une catégorie.
        /// </summary>
        public static string AddCategories {
            get {
                return ResourceManager.GetString("AddCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter/Modifier une catégorie.
        /// </summary>
        public static string AddEditCategory {
            get {
                return ResourceManager.GetString("AddEditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter / Modifier un adhérent.
        /// </summary>
        public static string AddEditMember {
            get {
                return ResourceManager.GetString("AddEditMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un auteur.
        /// </summary>
        public static string AddOthor {
            get {
                return ResourceManager.GetString("AddOthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tout.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total.
        /// </summary>
        public static string Alls {
            get {
                return ResourceManager.GetString("Alls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auteur.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion Des Auteurs.
        /// </summary>
        public static string AuthorManagement {
            get {
                return ResourceManager.GetString("AuthorManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 👤 Auteurs.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auteur Ajouté avec succès !.
        /// </summary>
        public static string AuthorSuccessfullyAdded {
            get {
                return ResourceManager.GetString("AuthorSuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auteur supprime avec succès !.
        /// </summary>
        public static string AuthorSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("AuthorSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auteur modifiée avec succes!.
        /// </summary>
        public static string AuthorSuccessfullyModified {
            get {
                return ResourceManager.GetString("AuthorSuccessfullyModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disponibilité.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📖 Livres.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Livre et Adhérent.
        /// </summary>
        public static string BookAndMember {
            get {
                return ResourceManager.GetString("BookAndMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réservez dés maintenant.
        /// </summary>
        public static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réservation de livre.
        /// </summary>
        public static string BookReservation {
            get {
                return ResourceManager.GetString("BookReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Titre Du Livre.
        /// </summary>
        public static string BookTitle {
            get {
                return ResourceManager.GetString("BookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Emprunter un nouveau Livre.
        /// </summary>
        public static string BorrowANewBook {
            get {
                return ResourceManager.GetString("BorrowANewBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Emprunter un livre.
        /// </summary>
        public static string BorrowBook {
            get {
                return ResourceManager.GetString("BorrowBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Empruntez dès maintenant.
        /// </summary>
        public static string BorrowNow {
            get {
                return ResourceManager.GetString("BorrowNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler .
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N° Carte.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🗂️  Catégorie.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des Catégories.
        /// </summary>
        public static string CategoryManagement {
            get {
                return ResourceManager.GetString("CategoryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie ajoutée avec succès !.
        /// </summary>
        public static string CategorySuccessfullyAdded {
            get {
                return ResourceManager.GetString("CategorySuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie supprimee avec succès !.
        /// </summary>
        public static string CategorySuccessfullyDeleted_ {
            get {
                return ResourceManager.GetString("CategorySuccessfullyDeleted!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à verifier la liste des Emprunts.
        /// </summary>
        public static string CheckLoanList {
            get {
                return ResourceManager.GetString("CheckLoanList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un classique sur l&apos;amitié, l&apos;amour et la solitude.
        /// </summary>
        public static string ClassicDescription {
            get {
                return ResourceManager.GetString("ClassicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivi complet des emprunts en cours et historiques.
        /// </summary>
        public static string CompleteTracking {
            get {
                return ResourceManager.GetString("CompleteTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer la suppression.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmées.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ✅ Confirmer l&apos;emprunt.
        /// </summary>
        public static string ConfirmLoan {
            get {
                return ResourceManager.GetString("ConfirmLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer la Réservation.
        /// </summary>
        public static string ConfirmTheReservation {
            get {
                return ResourceManager.GetString("ConfirmTheReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jours restants.
        /// </summary>
        public static string DaysRemaining {
            get {
                return ResourceManager.GetString("DaysRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description (facultatif).
        /// </summary>
        public static string DescriptionOptional {
            get {
                return ResourceManager.GetString("DescriptionOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🌟 A découvrir aujourd&apos;hui.
        /// </summary>
        public static string DiscoverToday {
            get {
                return ResourceManager.GetString("DiscoverToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier ou supprimer un auteur.
        /// </summary>
        public static string EditOrDelete {
            get {
                return ResourceManager.GetString("EditOrDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de fin.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez l&apos;ID de l&apos;abonné...
        /// </summary>
        public static string EnterSubscribeID {
            get {
                return ResourceManager.GetString("EnterSubscribeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Entrez l&apos;ID de l&apos;abonné.
        /// </summary>
        public static string EnterSubscriberID {
            get {
                return ResourceManager.GetString("EnterSubscriberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de Retour Prévue.
        /// </summary>
        public static string ExpectedReturnDate {
            get {
                return ResourceManager.GetString("ExpectedReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expirées.
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filtrer par statut.
        /// </summary>
        public static string FilterByStatus {
            get {
                return ResourceManager.GetString("FilterByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant amendes ($).
        /// </summary>
        public static string FineAmount {
            get {
                return ResourceManager.GetString("FineAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Amendes.
        /// </summary>
        public static string Fines {
            get {
                return ResourceManager.GetString("Fines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prenom de l&apos; Adherant : .
        /// </summary>
        public static string FirstNameOfTheMember {
            get {
                return ResourceManager.GetString("FirstNameOfTheMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Libérez des ouvrages pour d&apos;autres lecteurs.
        /// </summary>
        public static string FreeUpBooks {
            get {
                return ResourceManager.GetString("FreeUpBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Garantissez votre accés aux livres les plus populaires.
        /// </summary>
        public static string GuaranteeYourAccessToThemostPopularBooks {
            get {
                return ResourceManager.GetString("GuaranteeYourAccessToThemostPopularBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🏠  Accueil.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID de l&apos;emprunt.
        /// </summary>
        public static string IDOfTheLoan {
            get {
                return ResourceManager.GetString("IDOfTheLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En cours.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Titre, auteur ou ISBN ....
        /// </summary>
        public static string ISBN {
            get {
                return ResourceManager.GetString("ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La connaissance s&apos;acquiert par l&apos;expérience, tout le reste n&apos;est que de l&apos;information.
        /// </summary>
        public static string Knowledge {
            get {
                return ResourceManager.GetString("Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Nom.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En retard.
        /// </summary>
        public static string Late {
            get {
                return ResourceManager.GetString("Late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📋 Liste des Réservations.
        /// </summary>
        public static string ListOfReservations {
            get {
                return ResourceManager.GetString("ListOfReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date Emprunt.
        /// </summary>
        public static string LoanDate {
            get {
                return ResourceManager.GetString("LoanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID de l&apos;emprunt.
        /// </summary>
        public static string LoanID {
            get {
                return ResourceManager.GetString("LoanID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📋 Gestion des emprunts.
        /// </summary>
        public static string LoanManagement {
            get {
                return ResourceManager.GetString("LoanManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des Emprunts.
        /// </summary>
        public static string LoanManagementTitle {
            get {
                return ResourceManager.GetString("LoanManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ✨ Plongez dans votre prochaine lecture aujourd’hui ✨.
        /// </summary>
        public static string LoanNow {
            get {
                return ResourceManager.GetString("LoanNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ✨Partagez vos lectures, offrez une chance aux autres lecteurs ✨.
        /// </summary>
        public static string LoanSubtitle {
            get {
                return ResourceManager.GetString("LoanSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gérer les réservations.
        /// </summary>
        public static string ManageReservations {
            get {
                return ResourceManager.GetString("ManageReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prenom de l&apos;Adherant :.
        /// </summary>
        public static string MemberFirstName {
            get {
                return ResourceManager.GetString("MemberFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des adhérents.
        /// </summary>
        public static string MemberManagement {
            get {
                return ResourceManager.GetString("MemberManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des Adhérents.
        /// </summary>
        public static string MemberManagementTitle {
            get {
                return ResourceManager.GetString("MemberManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de l&apos;Adherant : .
        /// </summary>
        public static string MemberName {
            get {
                return ResourceManager.GetString("MemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 👥 Adherents.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de l&apos;Adherant :.
        /// </summary>
        public static string NameOfThemember {
            get {
                return ResourceManager.GetString("NameOfThemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom (obligatoire).
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ➕ Nouvelle.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle Reservation.
        /// </summary>
        public static string NewReservation {
            get {
                return ResourceManager.GetString("NewReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun emprunt trouvé.
        /// </summary>
        public static string NoLoansFound {
            get {
                return ResourceManager.GetString("NoLoansFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune réservation trouvée.
        /// </summary>
        public static string NoReservationsFound {
            get {
                return ResourceManager.GetString("NoReservationsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de Livre Emprunter.
        /// </summary>
        public static string NumberBorrowedBooks {
            get {
                return ResourceManager.GetString("NumberBorrowedBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de Livre Emprunter : .
        /// </summary>
        public static string NumberOfBorrowedBooks {
            get {
                return ResourceManager.GetString("NumberOfBorrowedBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Organisez vos livres par catégories.
        /// </summary>
        public static string OrganizeCategory {
            get {
                return ResourceManager.GetString("OrganizeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En attente.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivi et gestion des réservations en attente.
        /// </summary>
        public static string PendingReservations {
            get {
                return ResourceManager.GetString("PendingReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment supprimer cet auteur ? (cela supprimera tous les livres de cet auteur)&quot;.
        /// </summary>
        public static string popDelAuthor {
            get {
                return ResourceManager.GetString("popDelAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous supprimer la catégorie ?.
        /// </summary>
        public static string PopDelCathegori {
            get {
                return ResourceManager.GetString("PopDelCathegori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le prénom et le nom sont obligatoires..
        /// </summary>
        public static string popErrorAutor1 {
            get {
                return ResourceManager.GetString("popErrorAutor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet auteur existe deja.
        /// </summary>
        public static string popErrorAutor2 {
            get {
                return ResourceManager.GetString("popErrorAutor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom est obligatoire.
        /// </summary>
        public static string popErrorCategori1 {
            get {
                return ResourceManager.GetString("popErrorCategori1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un roman puissant sur la mémoire de l&apos;esclavage.
        /// </summary>
        public static string PowerfulNovelDescription {
            get {
                return ResourceManager.GetString("PowerfulNovelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Priorité.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer un emprunt.
        /// </summary>
        public static string RecordALoan {
            get {
                return ResourceManager.GetString("RecordALoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date Réservation.
        /// </summary>
        public static string ReservationDate {
            get {
                return ResourceManager.GetString("ReservationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des Réservations.
        /// </summary>
        public static string ReservationManagement {
            get {
                return ResourceManager.GetString("ReservationManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Période de Réservation.
        /// </summary>
        public static string ReservationPeriod {
            get {
                return ResourceManager.GetString("ReservationPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réserver un livre.
        /// </summary>
        public static string ReserveBook {
            get {
                return ResourceManager.GetString("ReserveBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à « Les livres sont une magie unique et portable. ».
        /// </summary>
        public static string ReserveYourBooksInAdvance {
            get {
                return ResourceManager.GetString("ReserveYourBooksInAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retourner un livre.
        /// </summary>
        public static string ReturnBook {
            get {
                return ResourceManager.GetString("ReturnBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retourner Un livre Emprunté.
        /// </summary>
        public static string ReturnBorrowedBook {
            get {
                return ResourceManager.GetString("ReturnBorrowedBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date Retour.
        /// </summary>
        public static string ReturnDate {
            get {
                return ResourceManager.GetString("ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retournés.
        /// </summary>
        public static string Returned {
            get {
                return ResourceManager.GetString("Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retournez vos livres.
        /// </summary>
        public static string ReturnYourBooks {
            get {
                return ResourceManager.GetString("ReturnYourBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher un auteur ....
        /// </summary>
        public static string SearchAuthor {
            get {
                return ResourceManager.GetString("SearchAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher un Livre .
        /// </summary>
        public static string SearchBook {
            get {
                return ResourceManager.GetString("SearchBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher par titre, auteur, adhérent....
        /// </summary>
        public static string SearchByCriteria {
            get {
                return ResourceManager.GetString("SearchByCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher par nom ou email... .
        /// </summary>
        public static string SearchMembers {
            get {
                return ResourceManager.GetString("SearchMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Titre, auteur ou ISBN....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🔍 Rechercher par livre, adhérent... .
        /// </summary>
        public static string SearchReservations {
            get {
                return ResourceManager.GetString("SearchReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à « La lecture est essentielle pour ceux qui cherchent à s’élever au‑dessus de l’ordinaire. ».
        /// </summary>
        public static string ShareKnowledge {
            get {
                return ResourceManager.GetString("ShareKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date Début.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Statut.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID de l&apos;abonné : .
        /// </summary>
        public static string SubscriberID {
            get {
                return ResourceManager.GetString("SubscriberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie modifiée avec secces !.
        /// </summary>
        public static string succespopCategorie1 {
            get {
                return ResourceManager.GetString("succespopCategorie1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🇫🇷 Français.
        /// </summary>
        public static string SwichLanguage {
            get {
                return ResourceManager.GetString("SwichLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total.
        /// </summary>
        public static string TotalLoans {
            get {
                return ResourceManager.GetString("TotalLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Suivez vos membres et leurs emprunts.
        /// </summary>
        public static string TrackMembers {
            get {
                return ResourceManager.GetString("TrackMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une visionnaire sur la surveillance et la liberté.
        /// </summary>
        public static string VisionaryDescription {
            get {
                return ResourceManager.GetString("VisionaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ✨ « La connaissance s’acquiert par l’expérience, tout le reste n’est que de l’information. ».
        /// </summary>
        public static string WelcomeSubtitle {
            get {
                return ResourceManager.GetString("WelcomeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🌐 Bienvenue dans LibraNova!.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
