//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliothequeManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BibliothequeManager.Properties.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accédez à des milliers de livres gratuitement.
        /// </summary>
        public static string AccessThousandsOfBooks {
            get {
                return ResourceManager.GetString("AccessThousandsOfBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auteur : .
        /// </summary>
        public static string Auteur {
            get {
                return ResourceManager.GetString("Auteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disponibilité :.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Emprunter un livre.
        /// </summary>
        public static string BorrowABook {
            get {
                return ResourceManager.GetString("BorrowABook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ✨📘 Emprunter un nouveau livre.
        /// </summary>
        public static string BorrowANewBook {
            get {
                return ResourceManager.GetString("BorrowANewBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⚡ Emprunter maintenant.
        /// </summary>
        public static string BorrowNow {
            get {
                return ResourceManager.GetString("BorrowNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ✅ Confirmer l&apos;emprunt.
        /// </summary>
        public static string ConfirmLoan {
            get {
                return ResourceManager.GetString("ConfirmLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🏠  Accueil.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID de l&apos;abonné.
        /// </summary>
        public static string IdMember {
            get {
                return ResourceManager.GetString("IdMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📋  Liste des emprunts.
        /// </summary>
        public static string LoanList {
            get {
                return ResourceManager.GetString("LoanList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des emprunts.
        /// </summary>
        public static string LoansManagement {
            get {
                return ResourceManager.GetString("LoansManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez l&apos;ID de l&apos;abonné.
        /// </summary>
        public static string MakeIdMember {
            get {
                return ResourceManager.GetString("MakeIdMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gérer les réservations.
        /// </summary>
        public static string ManageReservation {
            get {
                return ResourceManager.GetString("ManageReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des adhérents.
        /// </summary>
        public static string MembersManagement {
            get {
                return ResourceManager.GetString("MembersManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer un emprunt.
        /// </summary>
        public static string RecordALoan {
            get {
                return ResourceManager.GetString("RecordALoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reserver un livre.
        /// </summary>
        public static string ReserveABook {
            get {
                return ResourceManager.GetString("ReserveABook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retourner un livre.
        /// </summary>
        public static string ReturnABook {
            get {
                return ResourceManager.GetString("ReturnABook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📅 Date de Retour Prévue.
        /// </summary>
        public static string ReturnDate {
            get {
                return ResourceManager.GetString("ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher un livre.
        /// </summary>
        public static string SearchABook {
            get {
                return ResourceManager.GetString("SearchABook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Partagez la connaissance.
        /// </summary>
        public static string ShareKnowledge {
            get {
                return ResourceManager.GetString("ShareKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changer la langue.
        /// </summary>
        public static string SwitchLanguage {
            get {
                return ResourceManager.GetString("SwitchLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La connaissance s&apos;acquiert par l&apos;expérience, tout le reste n&apos;est que de l&apos;information.
        /// </summary>
        public static string TextWelcom {
            get {
                return ResourceManager.GetString("TextWelcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Titre, auteur ou ISBN....
        /// </summary>
        public static string TitleIsbn {
            get {
                return ResourceManager.GetString("TitleIsbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🔍 À découvrir aujourd&apos;hui.
        /// </summary>
        public static string ToDiscoverToday {
            get {
                return ResourceManager.GetString("ToDiscoverToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📖✨ Bienvenue à LibraNova.
        /// </summary>
        public static string WelcomToLibraNova {
            get {
                return ResourceManager.GetString("WelcomToLibraNova", resourceCulture);
            }
        }
    }
}
